---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-org-dept-b
  labels:
    name: ns-org-dept-b
    environment: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-org-dept-b
  name: app-org-dept-b
  labels:
    app: app-org-dept-b
    environment: prod
spec:
  selector:
    matchLabels:
      app: app-org-dept-b
      environment: prod
  template:
    metadata:
      labels:
        app: app-org-dept-b
        environment: prod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
