---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-org-dept-a
  labels:
    name: ns-org-dept-a
    environment: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-org-dept-a
  name: app-org-dept-a
  labels:
    app: app-org-dept-a
    environment: dev
spec:
  selector:
    matchLabels:
      app: app-org-dept-a
      environment: dev
  template:
    metadata:
      labels:
        app: app-org-dept-a
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
